name: Vocabulario
permalink_style: pretty 
markdown: redcarpet
pygments: true
textile_ext: "textile,txtl,tl"
exclude:
  - config.ru 
  - Gemfile
  - Gemfile.lock
  - vendor
  - Procfile 
  - Rakefile 
